### ISSUE TITLE
Accept-Datetime should return the closest Memento

### ISSUE THREAD

**Issue by gregjan** [trellis-ldp/trellis-ext-db#14]
According to RFC 7089, section 4.5.3, the Accept-Datetime header can request a date from a TimeGate prior to the first memento or after the last memento. In these cases, the specification says that the closest Memento should be selected. (Relates to #188 )

**Comment by acoburn** [comment]
Because the DBMementoService simply wraps the FileMemento service from the upstream repository, this issue was resolved with trellis-ldp/trellis#468
