### ISSUE TITLE
Auto-deploy to docker hub

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis-ext-db#6]
@gregjan would it make sense to set up the travis-ci configuration so that new commits to master (or any release branch) auto-deploy to docker hub? This would save us a manual step.

**Comment by gregjan** [comment]
I think that makes great sense. I'd love to help, but I haven't used Travis
yet.
Greg

**Comment by acoburn** [comment]
I've just added some "deploy" scoped sections for Travis on the main trellis repo: https://github.com/trellis-ldp/trellis/blob/master/.travis.yml#L47-L51, and I saw some examples of doing this for docker builds, too. So it shouldn't be too hard to add here.
